/**
 * Strings fixas da interface do relatório (header, métricas, footer, ações, etc.).
 * Usado quando o relatório é exibido/exportado em outro idioma (locale).
 */
export type ReportLocale = 'pt' | 'en' | 'es';

export const reportStrings: Record<
  ReportLocale,
  {
    headerDomainReport: string;
    headerPeriodLabel: string;
    headerComparisonLabel: string;
    comparisonPreviousPeriod: string;
    comparisonPreviousYear: string;
    comparisonPeriodAndYear: string;
    vsPreviousPeriod: string;
    vsPreviousYear: string;
    vsPeriodAndYear: string;
    footerGeneratedBy: string;
    footerCreatedBy: string;
    footerOn: string;
    metaConservative: string;
    metaGrowthRepresenting: string;
    metaPercentReached: string;
    actionInProgress: string;
    actionToStart: string;
    actionInDocs: string;
    actionCompleted: string;
    actionBacklogPrioritized: string;
  }
> = {
  pt: {
    headerDomainReport: 'Relatório de desempenho do domínio',
    headerPeriodLabel: 'Período de análise:',
    headerComparisonLabel: 'Período de comparação:',
    comparisonPreviousPeriod: 'Comparação: período anterior',
    comparisonPreviousYear: 'Comparação: ano anterior',
    comparisonPeriodAndYear: 'Comparação: período e ano anteriores',
    vsPreviousPeriod: 'vs. período anterior',
    vsPreviousYear: 'vs. ano anterior',
    vsPeriodAndYear: 'vs. período e ano anteriores',
    footerGeneratedBy: 'Relatório gerado pela liveSEO',
    footerCreatedBy: 'Criado por',
    footerOn: ' em ',
    metaConservative: 'Meta conservadora:',
    metaGrowthRepresenting: 'representando um crescimento de',
    metaPercentReached: '% da meta atingida',
    actionInProgress: 'Em andamento',
    actionToStart: 'A iniciar',
    actionInDocs: 'Em documentação',
    actionCompleted: 'Finalizadas',
    actionBacklogPrioritized: 'Backlog priorizado',
  },
  en: {
    headerDomainReport: 'Domain performance report',
    headerPeriodLabel: 'Analysis period:',
    headerComparisonLabel: 'Comparison period:',
    comparisonPreviousPeriod: 'Comparison: previous period',
    comparisonPreviousYear: 'Comparison: previous year',
    comparisonPeriodAndYear: 'Comparison: previous period and year',
    vsPreviousPeriod: 'vs. previous period',
    vsPreviousYear: 'vs. previous year',
    vsPeriodAndYear: 'vs. previous period and year',
    footerGeneratedBy: 'Report generated by liveSEO',
    footerCreatedBy: 'Created by',
    footerOn: ' on ',
    metaConservative: 'Conservative goal:',
    metaGrowthRepresenting: 'representing growth of',
    metaPercentReached: '% of goal reached',
    actionInProgress: 'In progress',
    actionToStart: 'To start',
    actionInDocs: 'In documentation',
    actionCompleted: 'Completed',
    actionBacklogPrioritized: 'Prioritized backlog',
  },
  es: {
    headerDomainReport: 'Informe de rendimiento del dominio',
    headerPeriodLabel: 'Período de análisis:',
    headerComparisonLabel: 'Período de comparación:',
    comparisonPreviousPeriod: 'Comparación: período anterior',
    comparisonPreviousYear: 'Comparación: año anterior',
    comparisonPeriodAndYear: 'Comparación: período y año anteriores',
    vsPreviousPeriod: 'vs. período anterior',
    vsPreviousYear: 'vs. año anterior',
    vsPeriodAndYear: 'vs. período y año anteriores',
    footerGeneratedBy: 'Informe generado por liveSEO',
    footerCreatedBy: 'Creado por',
    footerOn: ' el ',
    metaConservative: 'Meta conservadora:',
    metaGrowthRepresenting: 'representando un crecimiento de',
    metaPercentReached: '% de la meta alcanzada',
    actionInProgress: 'En curso',
    actionToStart: 'Por iniciar',
    actionInDocs: 'En documentación',
    actionCompleted: 'Finalizadas',
    actionBacklogPrioritized: 'Backlog priorizado',
  },
};
